name: Release

on:
  push:
    tags:
      - '*'

permissions:
  actions: read
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Release
        uses: softprops/action-gh-release@v2
